### ISSUE TITLE
CYD Support?

### ISSUE THREAD

**Issue by Arakon** [ojaksch/MiSTer_tty2tft#8]
Hi.

Are there any plans or any methods to get the CYD to work (Cheap Yellow Display)?
It's a very cheap display that consists of a screen in 2.8-4.8" sizes with an ESP32 onboard. 
Examples: https://www.aliexpress.com/item/1005006110360174.html and https://www.aliexpress.com/item/1005005928255980.html

These would be a very simple way to get a display set up for use with the MiSTer, for far less money than the seperate parts. The 2.8" variant seems to use an ILI9341 driver.

Some more info: https://randomnerdtutorials.com/cheap-yellow-display-esp32-2432s028r/

I had tried flashing the various display test bin files, but to no avail.

**Comment by ojaksch** [comment]
After our [conversation at the forum](https://misterfpga.org/viewtopic.php?p=90531&sid=9d1f33949e2d6db4fde105c37bb8e7a2#p90531) this got implemented.
Many thanks for contributing!
